### ISSUE TITLE
Typescript syntax highlighting not working?

### ISSUE THREAD

**Issue by nfour** [Sysmagine/SemanticDiff#11]
![image](https://user-images.githubusercontent.com/2108452/227411304-93334c3a-d95f-44f4-914e-e883dcc01f66.png)

Is this just not supported?

**Comment by slackner** [comment]
Thanks for reporting this issue! Syntax highlighting should indeed be supported, in fact SemanticDiff just uses the same theme files as VS code based on your current theme selection. I assume that syntax highlighting for typescript works correctly in the rest of VS code for you.

Here are a few theories of what could go wrong, could you please check if any of them applies to you?

* There were some problems with syntax highlighting, that have been fixed in SemanticDiff [version 0.8.2](https://marketplace.visualstudio.com/items/semanticdiff.semanticdiff/changelog). The new version is available for all operating systems and architectures, except Windows 32-bit (not our decision, publishing of extensions for Win 32 seems unreliable, and we're already in dicussions with the VS code team). Could you please double-check if you are using the latest version?

* We're aware that syntax highlighting does not work correctly in Dev Containers yet, i.e., when processing of the diff and displaying happens on two different machines or docker environments. It requires an experimental VS Code feature called [extensionsAny](https://github.com/microsoft/vscode/issues/145307) for syntax highlighting to work correctly in a dev container environment. Unfortunately, it is not possible to push extensions with experimental features to the marketplace. Such features are only available when installing extensions from `vsix` files. If you're interested, we might be able to publish experimental packages on our website.

* Lastly, it could be a problem related to the theme you are using. All VS Code default themes and most themes from the marketplace should work, but there might be some themes / extensions doing more unusual things, like replacing style files or similar. Please verify if the issue is present with all themes, or only some of them. If it's a very specific theme, please let us know which one so we can investigate further.

Note that syntax highlighting currently isn't re-computed when switching between themes. An already opened diff tab will continue to show the same colors as before. You will have to close the diff tab and open it again for syntax highlighting to work properly.

**Comment by nfour** [comment]
Can confirm it works after updating!
